'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutoMapRNI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Escala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Escala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property AMRNI() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AMRNI", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bat_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bat_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bat_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bat_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bat_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bat_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bat_75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bat_75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bat_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bat_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emr300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emr300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENACOM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENACOM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENACOM_contexto_final1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENACOM_contexto_final1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENACOM_sintexto_final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENACOM_sintexto_final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property ENACOM_sintexto_final1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ENACOM_sintexto_final1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Escala1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Escala1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Escala2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Escala2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Escala3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Escala3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Excel2013() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel2013", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property ExportarExcel() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportarExcel", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;/Document&gt;
        '''&lt;/kml&gt;.
        '''</summary>
        Friend ReadOnly Property footer() As String
            Get
                Return ResourceManager.GetString("footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property google_earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("google_earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;kml xmlns=&quot;http://www.opengis.net/kml/2.2&quot; xmlns:gx=&quot;http://www.google.com/kml/ext/2.2&quot; xmlns:kml=&quot;http://www.opengis.net/kml/2.2&quot; 
        '''xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        '''&lt;Document&gt;
        '''   &lt;name&gt;.
        '''</summary>
        Friend ReadOnly Property header_1() As String
            Get
                Return ResourceManager.GetString("header_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;/name&gt;.
        '''</summary>
        Friend ReadOnly Property header_2() As String
            Get
                Return ResourceManager.GetString("header_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a    &lt;Style id=&quot;MenorMin_normal&quot;&gt;
        '''      &lt;IconStyle&gt;
        '''         &lt;color&gt;9aff0000&lt;/color&gt;
        '''         &lt;scale&gt;1.2&lt;/scale&gt;
        '''         &lt;Icon&gt;
        '''            &lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png&lt;/href&gt;
        '''         &lt;/Icon&gt;
        '''      &lt;/IconStyle&gt;
        '''   &lt;/Style&gt;
        '''   &lt;Style id=&quot;MenorMin_hl&quot;&gt;
        '''      &lt;IconStyle&gt;
        '''         &lt;color&gt;ffff0000&lt;/color&gt;
        '''         &lt;scale&gt;1.4&lt;/scale&gt;
        '''         &lt;Icon&gt;
        '''            &lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png&lt;/href&gt;
        '''         &lt;/Icon&gt;
        '''      &lt;/IconSty [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property icon_1() As String
            Get
                Return ResourceManager.GetString("icon_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a    &lt;Style id=&quot;Nivel1_normal&quot;&gt;
        '''      &lt;IconStyle&gt;
        '''         &lt;color&gt;9afbc273&lt;/color&gt;
        '''         &lt;scale&gt;1.2&lt;/scale&gt;
        '''         &lt;Icon&gt;
        '''            &lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png&lt;/href&gt;
        '''         &lt;/Icon&gt;
        '''      &lt;/IconStyle&gt;
        '''   &lt;/Style&gt;
        '''   &lt;Style id=&quot;Nivel1_hl&quot;&gt;
        '''      &lt;IconStyle&gt;
        '''         &lt;color&gt;fffbc273&lt;/color&gt;
        '''         &lt;scale&gt;1.4&lt;/scale&gt;
        '''         &lt;Icon&gt;
        '''            &lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png&lt;/href&gt;
        '''         &lt;/Icon&gt;
        '''      &lt;/IconStyle&gt;        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property icon_11() As String
            Get
                Return ResourceManager.GetString("icon_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property microsoft_excel_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microsoft_excel_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nbm550() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nbm550", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a    &lt;Placemark&gt;
        '''      &lt;name&gt;.
        '''</summary>
        Friend ReadOnly Property placemark_1() As String
            Get
                Return ResourceManager.GetString("placemark_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;/name&gt;
        '''      &lt;styleUrl&gt;.
        '''</summary>
        Friend ReadOnly Property placemark_2() As String
            Get
                Return ResourceManager.GetString("placemark_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;/styleUrl&gt;
        '''      &lt;Point&gt;
        '''         &lt;coordinates&gt;.
        '''</summary>
        Friend ReadOnly Property placemark_3() As String
            Get
                Return ResourceManager.GetString("placemark_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ,0&lt;/coordinates&gt;
        '''      &lt;/Point&gt;
        '''      &lt;description&gt;&lt;![CDATA[.
        '''</summary>
        Friend ReadOnly Property placemark_4() As String
            Get
                Return ResourceManager.GetString("placemark_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ]]&gt;&lt;/description&gt;
        '''   &lt;/Placemark&gt;.
        '''</summary>
        Friend ReadOnly Property placemark_5() As String
            Get
                Return ResourceManager.GetString("placemark_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;ScreenOverlay&gt;
        '''&lt;name&gt;Escala cromática&lt;/name&gt;
        '''&lt;description&gt;Escala de colores que indica el porcentaje intensidad de campo eléctrico máximo detectado en el punto en cuestión, respecto a la MEP mas estricta&lt;/description&gt;
        '''&lt;drawOrder&gt;99&lt;/drawOrder&gt;
        '''&lt;Icon&gt;
        '''&lt;href&gt;&lt;/href&gt;
        '''&lt;/Icon&gt;
        '''&lt;overlayXY x=&quot;0&quot; y=&quot;1&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;screenXY x=&quot;0&quot; y=&quot;1&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;rotationXY x=&quot;0&quot; y=&quot;0&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;size x=&quot;0&quot; y=&quot;0&quot; xunits=&quot;fraction&quot; yunits=&quot;f [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property screenoverlay() As String
            Get
                Return ResourceManager.GetString("screenoverlay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;ScreenOverlay&gt;
        '''&lt;name&gt;Escala cromática&lt;/name&gt;
        '''&lt;description&gt;Escala de colores que indica el porcentaje intensidad de campo eléctrico máximo detectado en el punto en cuestión, respecto a la MEP mas estricta&lt;/description&gt;
        '''&lt;drawOrder&gt;99&lt;/drawOrder&gt;
        '''&lt;Icon&gt;
        '''&lt;href&gt;&lt;/href&gt;
        '''&lt;/Icon&gt;
        '''&lt;overlayXY x=&quot;0&quot; y=&quot;1&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;screenXY x=&quot;0&quot; y=&quot;1&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;rotationXY x=&quot;0&quot; y=&quot;0&quot; xunits=&quot;fraction&quot; yunits=&quot;fraction&quot;/&gt;
        '''&lt;size x=&quot;0.05&quot; y=&quot;0.3&quot; xunits=&quot;fraction&quot; yuni [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property screenoverlay1() As String
            Get
                Return ResourceManager.GetString("screenoverlay1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
